name: Deploy to Azure WebApp Branch slot

on:
  push:
    branches-ignore:
      - main
      - master


jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dockerregistryspa.azurecr.io/
        username: PushToken
        password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }} 
    - name: Build and push container without tag
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: dockerregistryspa.azurecr.io/dockerregistryspa/${{ github.event.repository.name }}:${{ github.sha }}
        context: ./
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'branch'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create slot if it doesn't exist
        run: |
          SLOT_NAME=${GITHUB_REF##*/}
          az webapp deployment slot create \
            --resource-group webappsdocker \
            --name ${{ github.event.repository.name }} \
            --configuration-source ${{ github.event.repository.name }} \
            --slot $SLOT_NAME || echo "Slot already exists"
      - name: Set container settings for slot
        run: |
          az webapp config container set \
            --name ${{ github.event.repository.name }} \
            --resource-group webappsdocker \
            --slot ${GITHUB_REF##*/} \
            --docker-custom-image-name dockerregistryspa.azurecr.io/dockerregistryspa/${{ github.event.repository.name }}:${{ github.sha }} \
            --docker-registry-server-url https://dockerregistryspa.azurecr.io

      - name: Restart slot to apply changes
        run: |
          az webapp restart \
            --name ${{ github.event.repository.name }} \
            --resource-group webappsdocker \
            --slot ${GITHUB_REF##*/}
